### ISSUE TITLE
What does return 0.f means 

### ISSUE THREAD

**Issue by ritu20chauhan** [matth-x/ArduinoOcpp#103]
setEnergyMeterInput([]() {
        //take the energy register of the main electricity meter and return the value in watt-hours
        return 0.f;
![return0 f](https://user-images.githubusercontent.com/75488251/203788347-64cd0dd7-7617-4232-85c4-ee206c24d72c.PNG)

**Comment by matth-x** [comment]
`0.f` is a placeholder which you can replace with a meaningful value.

The EnergyMeterInput should read the value of the energy meter and return it to the OCPP library. For example, given you store the energy register value in the global variable `float e_reg`, then change the statement to `return e_reg;`. The idea is that the OCPP library can fetch the energy value any time by executing the Input function.

**Comment by matth-x** [comment]
Closed due to inactivity. Please reopen for further questions.
