### ISSUE TITLE
Not getting compiling and uploading icon in platform.io

### ISSUE THREAD

**Issue by ritu20chauhan** [matth-x/ArduinoOcpp#106]
while using platform.io for arduinoOcpp, the platform does not shows compiling & uploading symbol.
These are visible when I am running some other code like- connecting esp to wifi basics.
This problem while using arduinoOcpp in platform.io happens frequently, so can anybody let me know why does this happen? Is there any installation
![Screenshot (13)](https://user-images.githubusercontent.com/75488251/206854814-2fa3c16c-5e9b-46ef-8974-0eba883ba054.png)
 problem or some changes are required in system?

**Comment by matth-x** [comment]
What happens if you open the project ArduinoOcpp-master directly via "Open Folder..."?

**Comment by matth-x** [comment]
Closed due to inactivity. Please open a new issue for follow-up questions.
