### ISSUE TITLE
I want to test the things in the test folder in the Arduino Occpp library file with Platformio

### ISSUE THREAD

**Issue by jpily** [matth-x/ArduinoOcpp#116]
Dear Matth-x,

Did you spend your weekend well?
There is a test folder among the library files distributed by matth-x, and I want to run and test through esp32s3 platformio with ChargingSessions.cpp, ocppEngineLifecycle.cpp, TransactionProcess.cpp, TransactionSafety.cpp that exists in the test folder. I'm leaving a question because I don't think it's arduino IDE. How can I run the code? 

Can you provide me with the https://youtu.be/hfTh9GjG-N4 arduino IDE.ino file you posted before and the library file that runs from arduino IDE? I appreciate your help.

**Comment by matth-x** [comment]
Your assumption is correct - those are not Arduino files. The test folder contains automated test which run on an Ubuntu only. You can find the Arduino sketches in the folder `examples`. I would recommend by trying the sketch in the `ESP` folder first.
