### ISSUE TITLE
How to set StatusNotification on main.cpp? I would like to set my charging point to "Preparing" status.

### ISSUE THREAD

**Issue by TDVSVI** [matth-x/ArduinoOcpp#120]
I would like to set my charging point to "Preparing" status. What should I do?
![ocpp](https://user-images.githubusercontent.com/69854174/220091328-87b7414b-28bc-4007-9d32-2558db5990b2.JPG)
I would like to do this test case. Is the library support this?

**Comment by nb4787** [comment]
Hi 
i can help you in this ........
connect with me cdacndb@gmail.com

**Comment by matth-x** [comment]
Hi, please follow the [getting-started example](https://github.com/matth-x/ArduinoOcpp/tree/master/examples/ESP) for the basic charge point integration. Once the library can read the status of the connector, it will start sending StatusNotification messages.

**Comment by TDVSVI** [comment]
I think I figured it out. Thank you.
