### ISSUE TITLE
How to use more than one connector (connectorId:2)

### ISSUE THREAD

**Issue by dipankarkhartad** [matth-x/ArduinoOcpp#123]
Hello Matthias,

Thank you very much for this library,

I want to use two connectors.  Is it possible to use more than one connector using this library?

**Comment by matth-x** [comment]
Hi @dipankarkhartad 

Here's an explanation how to use multiple conntectors: https://github.com/matth-x/ArduinoOcpp/issues/114#issuecomment-1415820156

**Comment by dipankarkhartad** [comment]
Thank you very much for your response.
