### ISSUE TITLE
hai i was able to coonect to my steve webserver using postman but still my esp32 is not connecting

### ISSUE THREAD

**Issue by rathourcode** [matth-x/ArduinoOcpp#140]
hai i was able to coonect to my steve webserver using postman but still my esp32 is not connecting 

my serial monitor is giving me errror
[AO] info (.pio/libdeps/esp32dev/ArduinoOcpp/src/ArduinoOcpp/Core/OcppSocket.cpp:31): Disconnected

can someone help please

_Originally posted by @rathourcode in https://github.com/matth-x/ArduinoOcpp/issues/138#issuecomment-1527323090_

**Comment by matth-x** [comment]
Sorry for jumping in later. Continuing the discussion in #138 and closing this.
