### ISSUE TITLE
Using C++03 complier

### ISSUE THREAD

**Issue by hk-moon** [matth-x/ArduinoOcpp#141]
As you know,  Power exectric & EV side is using TI TMS320F28377D chipset. But this chipset complier is using C++03 version. Do you have any idea/plan of this version(c++03) re-compling ?

**Comment by matth-x** [comment]
This library uses the C++14 standard at the moment. It provides some very essential features compared to C++03, most importantly lambda expressions and smart pointers (those hugely reduce the risk of memory leaks). While a C++11 back port should be possible, I don't believe that you could make the code ready for C++03 easily.

I'm sorry that I cannot provide further help on this.

**Comment by hk-moon** [comment]
Dear,Thank you for your kinds.나의 iPhone에서 보냄2023. 5. 5. 오전 5:22, Matthias Akstaller ***@***.***> 작성:﻿
Closed #141 as completed.
