### ISSUE TITLE
ERROR: JSON capacity exceeded

### ISSUE THREAD

**Issue by anupamsaikia** [matth-x/ArduinoOcpp#143]
How to solve this issue?

AO logs:
[AO] Recv: [2,"1eebd3b9-dcf2-48de-8cad-2d1852c95335","ChangeConfiguration",{"key":"ovt","value":"500"}]
[AO] ERROR (.pio/libdeps/esp32dev/ArduinoOcpp/src/ArduinoOcpp/Core/ConfigurationContainerFlash.cpp:167): JSON capacity exceeded
[AO] ERROR (.pio/libdeps/esp32dev/ArduinoOcpp/src/ArduinoOcpp/MessagesV16/ChangeConfiguration.cpp:167): could not write changes to flash
[AO] warning (.pio/libdeps/esp32dev/ArduinoOcpp/src/ArduinoOcpp/Core/OcppOperation.cpp:308): Operation failed. JSON CallError message: [4,"1eebd3b9-dcf2-48de-8cad-2d1852c95335","InternalError","",{}]

**Comment by matth-x** [comment]
Hi, the OCPP configs are stored in containers. Each container has its own JSON file on the filesystem to make the configs persistent over reboots.

If not specified, all configs go into the default container. It looks like the default container is already at capacity on your device. But it is possible to add extra containers which work on a new, empty JSON file then. You can route custom config entries into a new container like this:

```cpp
//needs header <ArduinoOcpp/Core/Configuration.h>

auto ovt = ArduinoOcpp::declareConfiguration<int>(
        "ovt", //key
        500, //factory default
        "/spiffs/my-container.jsn"); //file name for custom container
```

This should be called soon after `OCPP_initialize()`. Before testing, please make sure to erase the flash to avoid a duplicate entry in the default container.

Feel free to reopen if you have follow-up questions.
