### ISSUE TITLE
How to change OcppEvseState to SuspendedEV when I unplug?

### ISSUE THREAD

**Issue by TDVSVI** [matth-x/ArduinoOcpp#146]
Hello, I would like to use the function of StopTransactionOnEVSideDisconnect which impact to ev charger behavior.

If StopTransactionOnEVSideDisconnect is false when I unplug the ev, it should be turned to Suspendedev status. But now it can't.
For now when I unplug the ev, it sends stoptransaction and the status is finished.

What should I do? Please tell me the solution

**Comment by maxikys** [comment]
Hello!
use this callback in setup(){....}:
```C++
setConnectorPluggedInput([]() {
   return true;
},connectorId);
```
Algorithm: if you charger is ready you should return **true** 
                   if unready - **false**

**Comment by TDVSVI** [comment]
Thank you very much for your answer.

Can you help me to do this OCPP function? 
When it's charging and unplug it. The OCPPstate must be "SuspendedEV" if I set "StopTransactionOnEVSideDisconnect" is false.

![Suspendedev](https://github.com/matth-x/ArduinoOcpp/assets/69854174/f396bbad-8a4f-4f4a-8bb9-7d41e7a3a294)

**Comment by matth-x** [comment]
Hi @TDVSVI,

One of the most recent commits in the develop branch introduced the support for StopTransactionOnEVSideDisconnect. Unfortunately, in earlier versions the library accepted that config from the server while it did not implement its functionality. Can you upgrade, rerun that test and share the results here?

**Comment by TDVSVI** [comment]
Hi, @matth-x 
Thank you very much for your support. 

I downloaded the most recent library but it can't function. 
There are no responses about "SuspendedEV" when I set false to StopTransactionOnEVSideDisconnect.

Could you tell me about the code of this function? Where is the file in the library that stores this function?

**Comment by TDVSVI** [comment]
Thank you very much @matth-x 
I use the latest library and it can work.
