### ISSUE TITLE
How to "Reject" when i send remoteStartTransection to charger but charger didn't plug to the ev car 

### ISSUE THREAD

**Issue by ISCAETY** [matth-x/ArduinoOcpp#149]
Hi, Everyone,
Can i ask something about remoteStartTransection function. 
When i send remoteStartTransection to charger that not plug to the ev car i found it answer "Accept" instead "Reject". How can I change this condition from accept and timeout to reject if we didn't plug charger to the ev car?

**Comment by Navjot0005** [comment]
hi @ISCAETY have you done this??
Because I am also looking for the same. Pls share if you have resolve this!
