### ISSUE TITLE
How do I use DataTransfer function?

### ISSUE THREAD

**Issue by yosipat** [matth-x/ArduinoOcpp#150]
Hello everyone, I would like to use datatransfer function of OCPP.

I use the latest library version. I send data from server but it shows result below. What should I do?

`[AO] Recv: [2,"cd834539-8ce6-4276-9664-1f71f8044c97","DataTransfer",{"vendorId":"11","messageId":"22","data":"33"}]
[AO] ERROR (lib/ArduinoOcpp/src/ArduinoOcpp/Core/OcppMessage.cpp:38): Unsupported operation: processReq() is not implemented
[AO] ERROR (lib/ArduinoOcpp/src/ArduinoOcpp/Core/OcppMessage.cpp:42): Unsupported operation: createConf() is not implemented
[AO] Send: [4,"cd834539-8ce6-4276-9664-1f71f8044c97","NotImplemented","",{}]`

Thank you.

**Comment by matth-x** [comment]
Hi, you need to overload the DataTransfer operation with a custom implementation. This guide explains it (you need step 1 and 3):

https://github.com/matth-x/ArduinoOcpp/issues/93#issuecomment-1286880859

Please reopen the other issue if you have follow up questions or if something in the guide is not clear.
