### ISSUE TITLE
Help! I can't use function on ArduinoOcpp.h

### ISSUE THREAD

**Issue by yosipat** [matth-x/ArduinoOcpp#151]
Hi @matth-x , I would like to use function on ArduinoOcpp.h but I can't.

I mean this function as list below.

`void setOnDataTransfer(OnReceiveReqListener onReceiveReq);

void setOnSetChargingProfileRequest(OnReceiveReqListener onReceiveReq); // optional

void setOnRemoteStartTransactionSendConf(OnSendConfListener onSendConf);

void setOnRemoteStopTransactionSendConf(OnSendConfListener onSendConf);

void setOnRemoteStopTransactionReceiveReq(OnReceiveReqListener onReceiveReq);

void setOnResetSendConf(OnSendConfListener onSendConf);

bool startTransaction(const char *idTag, OnReceiveConfListener onConf = nullptr, OnAbortListener onAbort = nullptr, OnTimeoutListener onTimeout = nullptr, OnReceiveErrorListener onError = nullptr, std::unique_ptr<Timeout> timeout = nullptr);

bool stopTransaction(OnReceiveConfListener onConf = nullptr, OnAbortListener onAbort = nullptr, OnTimeoutListener onTimeout = nullptr, OnReceiveErrorListener onError = nullptr, std::unique_ptr<Timeout> timeout = nullptr);`

What should I do? Can you check your library?

**Comment by Quartzer01** [comment]
I have the same problem since i updated the library. TT

**Comment by yosipat** [comment]
Of course, that is the same issue. I will try it.
