### ISSUE TITLE
How to add more meter values using addMeterValueInput

### ISSUE THREAD

**Issue by VjSargunam** [matth-x/ArduinoOcpp#173]
I tried to add more meter values like SOC, Gun Temperature etc using the function call addMeterValueInput in the setup() function of main.cpp. whether we have to pass the value to the function or just return a value

**Comment by matth-x** [comment]
Hi, see this example:

```cpp
//global variable g_voltage
float g_voltage = 0.f;

//Arduino setup function
void setup() {
    //...
    addMeterValueInput([] () {
            return g_voltage;
        }, 
        "Voltage", //measurand as in OCPP specs
        "V"); //unit as in OCPP specs
}
```

You can find this and related examples in the OpenEVSE integration: https://github.com/OpenEVSE/openevse_esp32_firmware/blob/84b6794602aaeede216ee4ec0acb35b531686a08/src/ocpp.cpp#L175-L179

Please reopen if you have follow-up questions.
