### ISSUE TITLE
Disconnect sequence

### ISSUE THREAD

**Issue by BrianEstrada** [matth-x/ArduinoOcpp#19]
Would be nice to be able to safety disconnect from the OCPP server i.e do the following things before restarting or shutting down:

- Stop any ongoing transactions
- Set status to unavailable
- Disconnect safely from WS

**Comment by ChaitanyaYeole02** [comment]
I am also working on the same, it would be great to discuss the same with someone with same mentality

**Comment by matth-x** [comment]
Btw. 1ca99693f4a4c586b70d8f2f7d7f01a2ce0cfbb9 now introduces a safe deinitialization function. Thank you for your input in the first place!
