### ISSUE TITLE
Get Current Timestamp when OCPP is not connected

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [matth-x/ArduinoOcpp#24]
Yesterday I wrote a code to get the current timestamp and print it in my serial monitor. I noticed that, if I use current timestamp just after OCPP_Initialize it prints 1970 timestamp, and if I print it after Start or Stop Notification it gets me perfect timestamp.

This is the function to print current timestamp.
```
void current_timestamp() {
    using namespace::ArduinoOcpp;
    OcppTime *ocppTime = getOcppTime();
    OcppTimestamp time_stamp = ocppTime->getOcppTimestampNow();
    char timestamp[JSONDATE_LENGTH + 1] = {'\0'};
    time_stamp.toJsonString(timestamp, JSONDATE_LENGTH + 1);
    Serial.print(timestamp); 
}
```

I was thinking that if my OCPP starts and my server is not connected will I still be able to get exact timestamp?
If yes, then how?

**Comment by matth-x** [comment]
Closed due to inactivity

**Comment by rohith-kazam** [comment]
is there a way to locally sync time when the device is not connected to server?

**Comment by matth-x** [comment]
@rohith-kazam 

After initialization, set the time like this:

```cpp
getOcppContext()->getModel().getClock().setTime("2023-01-01T00:00:00.000Z");  //sets the time to Jan 01 2023, 00:00 am, UTC+00:00
```

Note that as soon as the OCPP connection is established, the internal time is synchronized with the OCPP server.
