### ISSUE TITLE
Using PZEM004 to capture metervalues

### ISSUE THREAD

**Issue by Pulse-akhil** [matth-x/ArduinoOcpp#27]
Hi Matth-x, I am planning to use the PZEM004 sensor and arduino library to capture the metervalues once the chargers is started. What are the ArduinoOCPP functions I should invoke in order to register the appropriate metervalues to the central system?

**Comment by rccess** [comment]
Hey @Pulse-akhil 

can you please help me with the same

https://github.com/matth-x/ArduinoOcpp/issues/42

**Comment by matth-x** [comment]
Please refer to `ArduinoOcpp.h` for the documentation of the API functions. This is the relevant excerpt:

https://github.com/matth-x/ArduinoOcpp/blob/e742bc760950731309c9c9ce1e4391a69ac2da82/src/ArduinoOcpp.h#L51-L53

It will be sufficient to set this callback function. Whenever the library needs the power or energy reading, it executes this callback.
