### ISSUE TITLE
How to remove configuration?

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [matth-x/ArduinoOcpp#31]
Ignore

**Comment by akashdk191** [comment]
bool removeConfiguration(const char *key,const char *filename) {
    
    
    std::shared_ptr<ConfigurationContainer> container = getContainer(filename);
    
    if (!container) {
        Serial.print(F("[Configuration] removeConfiguration: init new configurations container on flash filesystem: "));
        Serial.println(filename);

        if (!container->load()) {
            Serial.print(F("[Configuration] Cannot load file contents.\n"));
        }
    }

    std::shared_ptr<AbstractConfiguration> configuration = container->getConfiguration(key);

    if (configuration ) {
        if(DEBUG_OUT)
        {
            Serial.println(F("[Configuration] Removing configuration"));
            Serial.println(key);
            Serial.println("\n");
        }
        container->removeConfiguration(configuration);
        configuration->setToBeRemoved();
        configuration = NULL;
        return true;
    }

    return false;
}

I added a new function to remove configuration and it's working perfectly fine.

**Comment by prakharkalani** [comment]
Why are we removing this configuration file?

**Comment by matth-x** [comment]
Once a configuration is declared, it is valid for the lifetime of the library. You can only control if to write the configuration back to the persistent memory with `setToBeRemoved()`. If set, after the next reboot the information about the configuration will be gone and the configuration is finally deleted.

Thank you for your input @ChaitanyaYeole02 and @akashdk191. Flagging the object as removed did not invalidate the persistent memory. You probably observed that the remove operation was comitted too late.

And I introduced that the operation `Change Configuration` removes (writeable) configurations if `"value": ""`. Both changes are in 004b60ba19d81d0466766c28e768436e24173033.
