### ISSUE TITLE
FirmwareService.cpp warning

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [matth-x/ArduinoOcpp#34]
@matth-x 
I am getting a warning when I am trying to compile my code on ArduinoIDE. 
Also, 
`HTTP_UPDATE_FAILED Error (-11): HTTP error: read Timeout`
I am not sure if this error because of this warning.
```
warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
     fwService->setOnInstall([fwService = fwService] (String &location) {

```
And how to remove this warning?

**Comment by ChaitanyaYeole02** [comment]
My update firmware link is of https:// is this an issue?

**Comment by matth-x** [comment]
Hi @ChaitanyaYeole02, did you succeed in the meantime?

The warnings should be fixed by now. Have you checked if you can access the update URL with a web browser from the same network as the controller?
