### ISSUE TITLE
uniqueptr+jsondocument  ambiguous error

### ISSUE THREAD

**Issue by akashdk191** [matth-x/ArduinoOcpp#38]
![image](https://user-images.githubusercontent.com/1502833/147856641-ce3f6067-66c9-423a-90fa-735f87694824.png)
Hi Matthias
This error is appearing in development branch library.
Whenever a new json document is declared with uniqueptr, swap ambiguous error is appearing during compilation.
Need help in resolving the compilation error.

**Comment by matth-x** [comment]
That was addressed in bblanchon/ArduinoJson#1678 and is already fixed. Please update the dependency to the latest commit of the JSON library. Probably it will be sufficient to delete all folders in `.pio/libdeps` and to compile again.

**Comment by akashdk191** [comment]
Thanks Matthias. 
 I was updating the platform.ini in a wrong location(inside libdeps folder) than in main project folder. It's resolved
