### ISSUE TITLE
How to collect energy data to send OCPP based CMS

### ISSUE THREAD

**Issue by rccess** [matth-x/ArduinoOcpp#39]
Hello matt,

First of all we congralutate you for creating this amazing thing

I do have few Questions in my Mind ! 

We are working with ESP8266

How to collect energy for sending to OCPP based CMS

1. Can we use **Eastron Energy Meter** and connect with rs485 to take the energy data 
2. Can it stop the session in case of Car Got full Charged

Regards
Thanks

**Comment by matth-x** [comment]
Hi rcess, thank you very much!

Both is possible, yet requires further integration work on your end. The Eastron Modbus meter reports the meter values to the ESP using the RS485 adapter and a conventional Modbus library. From there, you can use the OCPP library to report the meter values registers from the ESP to the OCPP server. The auto-stop functionality will just require you to call the `stopTransaction()` at the desired point.
