### ISSUE TITLE
OCPP request not coming to server

### ISSUE THREAD

**Issue by rccess** [matth-x/ArduinoOcpp#42]
Hello Matt,

I have successfully uploaded the code in nodemcu and wifi also connected properly but nodemcu not sending request for ocpp connection to server, proper url defined 

same ocpp working with other ev charging machine

![image](https://user-images.githubusercontent.com/32220165/149099549-f64c46b9-b26d-49bd-a9b1-19663de6a80d.png)

can you please advise on the same ?

any troubleshooting hint, i have tested with other websocket request test but no luck

please help

thank you

**Comment by rccess** [comment]
matt, have any chance to help me please

**Comment by bnystrom** [comment]
I believe OCPP_HOST should just be "my.server.com". In the past it's worked w/o the "ws://" 
OCPP_PORT 8010
OCPP_URL "/OCPP16/<chargeboxId>" (whatever the chargebox for your EVSE is)

Hope that helps some.

**Comment by matth-x** [comment]
Hi @rccess, did you succeed with the input from @bnystrom?

Please refer to https://github.com/matth-x/ArduinoOcpp/issues/36#issuecomment-989716573 which describes what to do to get the initial connection right.
