### ISSUE TITLE
Errors when building SECC example

### ISSUE THREAD

**Issue by ZolikovaPlesataHlava** [matth-x/ArduinoOcpp#43]
Hi.

I am having issues compiling the SECC example you provided as the try out sketch. I tried with arduino IDE and with platformIO. And I seem to get the same error on both builds. 

**Arduino IDE:** 
WARNING: library ArduinoOcpp-master claims to run on espressif8266, espressif32 architecture(s) and may be incompatible with your current board which runs on esp8266 architecture(s).
C:\Users\Matus\AppData\Local\Temp\arduino_modified_sketch_160544\main.ino: In function 'void setup()':
main:193:101: error: no matching function for call to 'WebSocketsClient::beginSSL(String&, uint16_t&, String&, const char [1], const char [8])'
             wSock->beginSSL(ocppUrlParsed.host, ocppUrlParsed.port, ocppUrlParsed.url, "", "ocpp1.6");
                                                                                                     ^
C:\Users\Matus\AppData\Local\Temp\arduino_modified_sketch_160544\main.ino:193:101: note: candidate is:
In file included from C:\Users\Matus\Documents\Arduino\libraries\ArduinoOcpp-master\src/ArduinoOcpp/Core/OcppSocket.h:29:0,
                 from C:\Users\Matus\Documents\Arduino\libraries\ArduinoOcpp-master\src/ArduinoOcpp/Core/OcppOperation.h:16,
                 from C:\Users\Matus\Documents\Arduino\libraries\ArduinoOcpp-master\src/ArduinoOcpp.h:8,
                 from C:\Users\Matus\AppData\Local\Temp\arduino_modified_sketch_160544\main.ino:20:
C:\Users\Matus\Documents\Arduino\libraries\arduinoWebSockets-master\src/WebSocketsClient.h:50:10: note: void WebSocketsClient::beginSSL(const char*, uint16_t, const char*, const uint8_t*, const char*)
     void beginSSL(const char * host, uint16_t port, const char * url = "/", const uint8_t * fingerprint = NULL, const char * protocol = "arduino");
          ^
C:\Users\Matus\Documents\Arduino\libraries\arduinoWebSockets-master\src/WebSocketsClient.h:50:10: note:   no known conversion for argument 1 from 'String' to 'const char*'
exit status 1
no matching function for call to 'WebSocketsClient::beginSSL(String&, uint16_t&, String&, const char [1], const char [8])'
**PlatformIO :**
> Executing task in folder OCPP4: C:\Users\Matus\.platformio\penv\Scripts\platformio.exe run --environment nodemcuv2 <

Warning! Ignore unknown configuration option `build_partitions` in section [env:esp32-development-board]
Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (3.2.0) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.30002.0 (3.0.2) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa 2.100300.210717 (10.3.0)
Converting main.ino
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:34: warning: "EV_PLUGGED" redefined
   34 | #define EV_PLUGGED LOW
      | 
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:31: note: this is the location of the previous definition
   31 | #define EV_PLUGGED HIGH
      | 
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:35: warning: "EV_UNPLUGGED" redefined
   35 | #define EV_UNPLUGGED HIGH
      | 
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:32: note: this is the location of the previous definition
   32 | #define EV_UNPLUGGED LOW
      |
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:47: warning: "EV_CHARGING" redefined
   47 | #define EV_CHARGING HIGH
      |
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:44: note: this is the location of the previous definition
   44 | #define EV_CHARGING LOW
      |
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:48: warning: "EV_SUSPENDED" redefined
   48 | #define EV_SUSPENDED LOW
      |
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:45: note: this is the location of the previous definition
   45 | #define EV_SUSPENDED HIGH
      | 
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:73: warning: "CHARGE_PERMISSION_ON" redefined
   73 | #define CHARGE_PERMISSION_ON LOW
      |
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:70: note: this is the location of the previous definition
   70 | #define CHARGE_PERMISSION_ON HIGH
      |
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:74: warning: "CHARGE_PERMISSION_OFF" redefined
   74 | #define CHARGE_PERMISSION_OFF HIGH
      |
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:71: note: this is the location of the previous definition
   71 | #define CHARGE_PERMISSION_OFF LOW
      |
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 39 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 6.17.2
|-- <WebSockets> 2.2.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <Ethernet> 2.0.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <Hash> 1.0
|-- <WiFiManager> 0.16.0
|   |-- <DNSServer> 1.1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoOcpp> 0.0.4
|   |-- <ArduinoJson> 6.17.2
|   |-- <WebSockets> 2.2.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Ethernet> 2.0.0
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |   |-- <Hash> 1.0
|   |-- <ESP8266httpUpdate> 1.3
|   |   |-- <ESP8266HTTPClient> 1.2
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <LittleFS> 0.1.0
Building in release mode
Compiling .pio\build\nodemcuv2\src\main.ino.cpp.o
Generating LD script .pio\build\nodemcuv2\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFi.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFiAP.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFiGratuitous.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pio\build\nodemcuv2\lib3ee\ESP8266WiFi\enable_wifi_at_boot_time.cpp.o
Compiling .pio\build\nodemcuv2\lib17d\SPI\SPI.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\Dhcp.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\Dns.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\Ethernet.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\EthernetClient.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\EthernetServer.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\EthernetUdp.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\socket.cpp.o
Compiling .pio\build\nodemcuv2\libaa1\Ethernet\utility\w5100.cpp.o
Compiling .pio\build\nodemcuv2\lib529\Hash\Hash.cpp.o
Compiling .pio\build\nodemcuv2\libf9e\WebSockets\SocketIOclient.cpp.o
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino: In function 'bool runWiFiManager()':
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:356:17: error: 'class WiFiManager' has no member named 'setTitle'
  356 |     wifiManager.setTitle("EVSE configuration portal");
      |                 ^~~~~~~~
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:357:17: error: 'class WiFiManager' has no member named 'setParamsPage'
  357 |     wifiManager.setParamsPage(true);
      |                 ^~~~~~~~~~~~~
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:374:17: error: 'class WiFiManager' has no member named 'setSaveParamsCallback'; did you mean 'setSaveConfigCallback'?
  374 |     wifiManager.setSaveParamsCallback([&ocppUrlParam = ocppUrlParam, &ocppUrl = ocppUrl, &wifiManager = wifiManager, &CA_cert = CA_cert, &caCertParam = caCertParam, &httpAuthentication = httpAuthentication, &httpAuthenticationParam = httpAuthenticationParam] () {
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 setSaveConfigCallback
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino: In lambda function:
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:385:24: error: 'std::unique_ptr<esp8266webserver::ESP8266WebServerTemplate<WiFiServer> > WiFiManager::server' is private within this context
  385 |         if(wifiManager.server->hasArg(caCertChangedParam)) {
      |                        ^~~~~~
In file included from C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:18:
.pio\libdeps\nodemcuv2\WiFiManager/WiFiManager.h:123:39: note: declared private here
  123 |     std::unique_ptr<ESP8266WebServer> server;
      |                                       ^~~~~~
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:386:55: error: 'std::unique_ptr<esp8266webserver::ESP8266WebServerTemplate<WiFiServer> > WiFiManager::server' is private within this context
  386 |             String caCertChanged = String(wifiManager.server->arg(caCertChangedParam));
      |                                                       ^~~~~~
In file included from C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:18:
.pio\libdeps\nodemcuv2\WiFiManager/WiFiManager.h:123:39: note: declared private here
  123 |     std::unique_ptr<ESP8266WebServer> server;
      |                                       ^~~~~~
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:397:24: error: 'std::unique_ptr<esp8266webserver::ESP8266WebServerTemplate<WiFiServer> > WiFiManager::server' is private within this context
  397 |         if(wifiManager.server->hasArg(authChangedParam)) {
      |                        ^~~~~~
In file included from C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:18:
.pio\libdeps\nodemcuv2\WiFiManager/WiFiManager.h:123:39: note: declared private here
  123 |     std::unique_ptr<ESP8266WebServer> server;
      |                                       ^~~~~~
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:398:53: error: 'std::unique_ptr<esp8266webserver::ESP8266WebServerTemplate<WiFiServer> > WiFiManager::server' is private within this context
  398 |             String authChanged = String(wifiManager.server->arg(authChangedParam));
      |                                                     ^~~~~~
In file included from C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:18:
.pio\libdeps\nodemcuv2\WiFiManager/WiFiManager.h:123:39: note: declared private here
  123 |     std::unique_ptr<ESP8266WebServer> server;
      |                                       ^~~~~~
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino: In function 'bool runWiFiManager()':
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:409:17: error: 'class WiFiManager' has no member named 'setDarkMode' 
  409 |     wifiManager.setDarkMode(true);
      |                 ^~~~~~~~~~~
C:/Users/Matus/Documents/PlatformIO/Projects/OCPP4/src/main.ino:415:17: error: 'class WiFiManager' has no member named 'setAPClientCheck'
  415 |     wifiManager.setAPClientCheck(true); // avoid timeout if client connected to softap
      |                 ^~~~~~~~~~~~~~~~
Compiling .pio\build\nodemcuv2\libf9e\WebSockets\WebSockets.cpp.o
Compiling .pio\build\nodemcuv2\libf9e\WebSockets\WebSocketsClient.cpp.o
Compiling .pio\build\nodemcuv2\libf9e\WebSockets\WebSocketsServer.cpp.o
Compiling .pio\build\nodemcuv2\libf9e\WebSockets\libb64\cdecode.c.o
Compiling .pio\build\nodemcuv2\libf9e\WebSockets\libb64\cencode.c.o
*** [.pio\build\nodemcuv2\src\main.ino.cpp.o] Error 1
.pio\libdeps\nodemcuv2\WebSockets\src\SocketIOclient.cpp: In member function 'void SocketIOclient::handleCbEvent(WStype_t, uint8_t*, size_t)':
.pio\libdeps\nodemcuv2\WebSockets\src\SocketIOclient.cpp:102:11: warning: enumeration value 'WStype_ERROR' not handled in switch [-Wswitch]
  102 |     switch(type) {
      |           ^
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::loop()':
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsClient.cpp:172:30: error: 'class BearSSL::WiFiClientSecure' has no member named 'setCACert'
  172 |                 _client.ssl->setCACert((const uint8_t *)_CA_cert, strlen(_CA_cert) + 1);
      |                              ^~~~~~~~~
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::connectedCb()':
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsClient.cpp:759:26: error: 'class BearSSL::WiFiClientSecure' has no member named 'verify'
  759 |         if(!_client.ssl->verify(_fingerprint.c_str(), _host.c_str())) {
      |                          ^~~~~~
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsServer.cpp: In constructor 'WebSocketsServer::WebSocketsServer(uint16_t, String, String)':
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsServer.cpp:49:83: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct WSclient_t' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
   49 |     memset(&_clients[0], 0x00, (sizeof(WSclient_t) * WEBSOCKETS_SERVER_CLIENT_MAX));
      |                                                                                   ^
In file included from .pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsServer.cpp:25:
.pio\libdeps\nodemcuv2\WebSockets\src\WebSockets.h:237:16: note: 'struct WSclient_t' declared here
  237 | typedef struct {
      |                ^
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsServer.cpp: In member function 'bool WebSocketsServer::newClient(WiFiClient*)':      
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsServer.cpp:465:23: warning: variable 'ip' set but not used [-Wunused-but-set-variable]
  465 |             IPAddress ip = client->tcp->remoteIP();
      |                       ^~
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsServer.cpp: In member function 'void WebSocketsServer::handleNewClients()':
.pio\libdeps\nodemcuv2\WebSockets\src\WebSocketsServer.cpp:638:23: warning: variable 'ip' set but not used [-Wunused-but-set-variable]
  638 |             IPAddress ip = tcpClient->remoteIP();
      |                       ^~
*** [.pio\build\nodemcuv2\libf9e\WebSockets\WebSocketsClient.cpp.o] Error 1
==================================================== [FAILED] Took 5.44 seconds ====================================================

Environment    Status    Duration
-------------  --------  ------------
nodemcuv2      FAILED    00:00:05.445
=============================================== 1 failed, 0 succeeded in 00:00:05.445 ===============================================

I currently dont own any EVSE and I would love to try out OCPP to be used with my own backend system.

**Comment by matth-x** [comment]
Hi @ZolikovaPlesataHlava,

In the previous `platformio.ini` file, not all dependencies were fully specified which led to compilation problems on some machines. Can you please load the most recent version of the library and the `platformio.ini` and try it again?

That's how the LDF output looks like on my machine:

```
Processing nodemcuv2 (platform: espressif8266@2.6.3; board: nodemcuv2; framework: arduino)
[...]
PLATFORM: Espressif 8266 (2.6.3) > NodeMCU 1.0 (ESP-12E Module)
[...]
Dependency Graph
|-- <ArduinoJson> 6.19.1
|-- <WebSockets> 2.3.6
|   |-- <ESP8266WiFi> 1.0        
|   |-- <Ethernet(esp8266)> 1.0.4
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <Hash> 1.0
|-- <LittleFS(esp8266)> 0.1.0    
|-- <ESP8266httpUpdate> 1.3      
|   |-- <ESP8266HTTPClient> 1.2  
|   |   |-- <ESP8266WiFi> 1.0    
|   |-- <ESP8266WiFi> 1.0        
|-- <ESP8266WiFi> 1.0
Building in release mode
[...]
```

**Comment by ZolikovaPlesataHlava** [comment]
Perfect, the new platformio.ini fixed the problem.
Thank you.

**Comment by susanthomasv** [comment]
Which is the new platformio.ini? I'm getting the same errors

**Comment by matth-x** [comment]
Can you try this? https://github.com/matth-x/ArduinoOcpp/blob/develop/platformio.ini

Please remember that you have to instruct PIO to download the new versions and replace the old ones.
