### ISSUE TITLE
relay once start and autoclose

### ISSUE THREAD

**Issue by rccess** [matth-x/ArduinoOcpp#44]
Hello Matt,

Getting issue with autorization

[StartTransaction] Request has been denied!

![image](https://user-images.githubusercontent.com/32220165/150779662-7d6f6a81-8446-43f0-a5e3-4307d7809ac1.png)

![image](https://user-images.githubusercontent.com/32220165/150779741-f1f1ae8d-b8c9-4867-91e8-53c2778b5041.png)

and Central system, 

the status showing

**Preparing**

Please do advise 

thanks

**Comment by matth-x** [comment]
Hi @rccess,

Have you had a chance to check the logs of your OCPP backend system? It looks like the backend has blocked the `idTag`. From that point on, the EVSE cannot start a transaction. In SteVe, that's most often due to a previous transaction which still counts as active and therefore occupies the `idTag`. You can probably delete obsolete transactions by hand in the backend (in SteVe, you can for sure).

The debug messages here are not too helpful here, admittedly. From f925f1b51e81df4f72d9f4885983e0396130189e on, the library also prints the reason for the denial of the `idTag`.

**Comment by rccess** [comment]
Hello @matth-x 

There is another issue at the moment 
![image](https://user-images.githubusercontent.com/32220165/152146235-8d3de0f4-5d4c-49a8-b933-91b8e8f8fe27.png)

![image](https://user-images.githubusercontent.com/32220165/152146398-fb26a2fd-0cb2-4d55-bf96-e47e7e1eb713.png)


  "stack": "Error: OCPP Command 'RemoteStartTransaction' has failed

      "error": "Error: Timeout after 10 secs for Message ID 'f3b713f4-a655-4886-8b36-cdae54e57b78' with content '[2,\"f3b713f4-a655-4886-8b36-cdae54e57b78\",\"RemoteStartTransaction\",{\"connectorId\":1,\"idTag\":\"KH1675768958\"}] (app)

other charging station starting with same idTag

Please do advise

**Comment by matth-x** [comment]
`RemoteStartTransaction` is available when you configure it with

https://github.com/matth-x/ArduinoOcpp/blob/e742bc760950731309c9c9ce1e4391a69ac2da82/src/ArduinoOcpp.h#L91

Inside the callback, you must decide whether to actually start a transaction (e.g. you might not if no cable is plugged) and call `startTransaction()` if yes.

**Comment by rccess** [comment]
![image](https://user-images.githubusercontent.com/32220165/152151306-95b6e718-8e3b-4df9-9320-ccbeeba43d10.png)

![image](https://user-images.githubusercontent.com/32220165/152151332-fb657e46-0122-4817-a21a-656ce75a11da.png)


i have disable that line  but still same issue

**Comment by matth-x** [comment]
Oh that line must remain in `ArduinoOcpp.h`.

You can implement `RemoteStartTransaction` like that:

https://github.com/matth-x/ArduinoOcpp/blob/e742bc760950731309c9c9ce1e4391a69ac2da82/examples/SECC/main.cpp#L273-L280

**Comment by rccess** [comment]
![image](https://user-images.githubusercontent.com/32220165/152283663-e0cb05a3-be0a-4835-88b5-231619c50385.png)

i have defined setOnRemoteStartTransactionSendConf and setOnRemoteStopTransactionSendConf in setup

But issue is still same,

Transaction got rejected with error

![image](https://user-images.githubusercontent.com/32220165/152283904-c2b090b5-47fa-46ee-8197-84c6c02d105d.png)

**Comment by matth-x** [comment]
My guess is that the `BootNotification` has never succeeded in the latest run. Without the `BootNotification`, the EVSE remains silent and doesn't react on `RemoteStartTransaction`s. Can you maybe roll back the changes to the code in the first post above (there it worked).

If you add the following lines to `platformio.ini` and post the full debug output, the problem will become much more apparent:

https://github.com/matth-x/ArduinoOcpp/blob/e742bc760950731309c9c9ce1e4391a69ac2da82/platformio.ini#L21-L23

**Comment by rccess** [comment]
BootNotification is calling in lastest version

![image](https://user-images.githubusercontent.com/32220165/152650412-3f60b2e3-b88d-407f-94de-edecedb862ba.png)

can you please advise on the same

Thanks in advance !

**Comment by matth-x** [comment]
Closed due to inactivity
