### ISSUE TITLE
Bug in smart charging? "chargingRateUnit" in stead of "scheduleUnit"

### ISSUE THREAD

**Issue by diskgokey** [matth-x/ArduinoOcpp#46]
Hi,

Could it be that this is not compliant with the standard OCPP msg?
This should be "chargingRateUnit" instead of "scheduleUnit" imo.

https://github.com/matth-x/ArduinoOcpp/blob/e742bc760950731309c9c9ce1e4391a69ac2da82/src/ArduinoOcpp/Tasks/SmartCharging/SmartChargingModel.cpp#L72

**Comment by matth-x** [comment]
@diskgokey Hi, thank you for your input and you're absolutely right. I've fixed it in e1b304636b1183e31e324fa31efbe3ea659a0886
