### ISSUE TITLE
OCPP_initialize function not calling

### ISSUE THREAD

**Issue by rccess** [matth-x/ArduinoOcpp#48]
Hello @matth-x 

I have successfully upload the code in esp8266 and it is connected to wifi but 

OCPP_initialize not calling

no ocpp request coming on central server 

![image](https://user-images.githubusercontent.com/32220165/152648733-545227de-bb15-4c65-aed5-4633ef5a0f9c.png)

Please do advise 

Thank You

**Comment by matth-x** [comment]
Hi @rccess, in https://github.com/matth-x/ArduinoOcpp/issues/36#issuecomment-989716573 you can find how to make the WebSocket connection work.

**Comment by rccess** [comment]
Service request already come to server and opened websocket request but not
booting and not charging station showing in cms but with same settings it
was working in your old repo


Please do advise

**Comment by matth-x** [comment]
Is the `OCPP_loop()` inside the `loop()` function and will it be called in every `loop()` execution?

If both is true, please compile again with the following debug flags:

https://github.com/matth-x/ArduinoOcpp/blob/e742bc760950731309c9c9ce1e4391a69ac2da82/platformio.ini#L21-L23

**Comment by matth-x** [comment]
Closed due to inactivity
