### ISSUE TITLE
Initiate a firmware update with FTP/HTTP/HTTPS/WS with this library

### ISSUE THREAD

**Issue by valerio-2020** [matth-x/ArduinoOcpp#53]
Hi @matth-x,

How to start with configuring the system for firmware updates?
Also what does the current implementation in the library have?

Thanks :)

**Comment by matth-x** [comment]
Hi, the library handles the OCPP side of firmware updates which is accepting `UpdateFirmware` requests and handing them over to the client code at the right time. In the client code, you have to define a callback function which performs the final firmware download and installation then.

Yet the library already comes with one example firmware download and installation handler. It can perform firmware updates on the ESP via HTTP (no TLS though!). You can take a look at it to see how everything works. It is active by default. So if you send an `UpdateFirmware` request pointing to an HTTP resource, the library already handles the request.

You can find another example how to define the firmware download and installation in the OpenEVSE project: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/a87958dbbb5ca1e57a8a45a1feb27aead08e4391/src/ocpp.cpp#L530-L566

For the proper HTTPS and FTPS implementations you can follow that example.
