### ISSUE TITLE
ready to use for ESP32?

### ISSUE THREAD

**Issue by appplay01** [matth-x/ArduinoOcpp#56]
compile error with ESP32.
error return
In file included from src/main.cpp:18:0:
.pio/libdeps/esp32dev/WiFiManager/WiFiManager.h:16:25: fatal error: ESP8266WiFi.h: No such file or directory

*********************************************************************
* Looking for ESP8266WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP8266WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:ESP8266WiFi.h
*
*********************************************************************

compilation terminated.
*** [.pio\build\esp32dev\src\main.cpp.o] Error 1

**Comment by matth-x** [comment]
In the meantime, I have improved the PlatformIO integration and probably this error wouldn't happen anymore.

Feel free to open another issue.
