### ISSUE TITLE
Is this library available for STM32? How to setup in STM32

### ISSUE THREAD

**Issue by adithyagurumurthy** [matth-x/ArduinoOcpp#63]

**Comment by matth-x** [comment]
Hi, this is under work. You can already compile the main part of this library on different platforms (STM32 possibly as well), but the integration of the platform-specific parts, i.e. the TCP/IP stack, filesystem and clock, still needs to be implemented for STM32. At the moment I'm working on the same for the ESP-IDF.

If you have follow-up questions, feel free to reopen this issue.
