### ISSUE TITLE
esp-idf component

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [matth-x/ArduinoOcpp#7]
Is this project somehow compatible with esp-idf?

We ditched platformio long ago to avoid so many problems  aand improve compile times (our firmware takes already quarter hour to compile :D)

esp-idf has a concept of components, each containing its own CMakeLists.txt and linking required dependencies

**Comment by matth-x** [comment]
I already have plans for an ESP-IDF integration. But right now there are a few incompatible bits of code and it also depends on how you do some specific things like memory allocation. If you want to discuss your project privately, feel free to contact me (matthias A⊤ arduino-ocpp DО⊤ com).
