### ISSUE TITLE
how to add functionality for Data Transfer from CMS to Charger

### ISSUE THREAD

**Issue by VjSargunam** [matth-x/ArduinoOcpp#75]
Hi Matt,

      The data transfer from charge point to CMS is already there in your code. But how to add the functionality for performing data transfer from CMS to charge point.

Regards
S.Vijayakumar

**Comment by piyush9999** [comment]
Anyone got the solution, i too want the data transfer thing to be implemented

**Comment by piyush9999** [comment]
@VjSargunam you got the data transfer done

**Comment by piyush9999** [comment]
@matth-x Bro i need much help from you, can we connect
