### ISSUE TITLE
Build error using PlatformIO

### ISSUE THREAD

**Issue by Welesley** [matth-x/ArduinoOcpp#9]
Hello, I'm trying to build the project using platformio and I'm always getting this error at link time: 
I stay using: PlatformIO Core, version 5.1.1 . Thanks

DEBUG: Current (ftdi) On-board (ftdi) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 2.10004.191002 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 29 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 6.17.2
|-- <WebSockets> 2.2.0
|   |-- <WiFi> 1.0
|   |-- <SPI> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.0
|-- <LittleFS_esp32> 1.0.5
|   |-- <FS> 1.0
|-- <FS> 1.0
Building in release mode
Linking .pio/build/esp32-development-board/firmware.elf
.pio/build/esp32-development-board/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0x4): undefined reference to `setup()'
.pio/build/esp32-development-board/libFrameworkArduino.a(main.cpp.o):(.literal._Z8loopTaskPv+0x8): undefined reference to `loop()'
.pio/build/esp32-development-board/libFrameworkArduino.a(main.cpp.o): In function `loopTask(void*)':
/home/welesley/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:14: undefined reference to `setup()'
/home/welesley/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:17: undefined reference to `loop()'
collect2: error: ld returned 1 exit status
*** [.pio/build/esp32-development-board/firmware.elf] Error 1
========================================================= [FAILED] Took 4.81 seconds =========================================================

Environment              Status    Duration
-----------------------  --------  ------------
esp32-development-board  FAILED    00:00:04.807
=================================================== 1 failed, 0 succeeded in 00:00:04.807 ===================================================

**Comment by matth-x** [comment]
Hi Welesley, this project is not a "standalone" program but a library which adds the OCPP functionality to your own program. For getting started quickly, I've added an example program which will compile right away. Please copy `examples/ESP32/main.ino` into your `src` folder and try the compilation again.
