### ISSUE TITLE
.json package not found while trying to compile ESP example for ESP8266

### ISSUE THREAD

**Issue by ritu20chauhan** [matth-x/ArduinoOcpp#98]
The code from the example of ESP was successfully compiled for ESP32.
But when I tried the same code for ESP8266 the was error "Package.Json" not found.
 
![json Package not found](https://user-images.githubusercontent.com/75488251/198979571-9ef91f70-e0c8-4fcc-8cad-42c6e1f2eebb.PNG)

**Comment by nb4787** [comment]
can you connect me mail id ? im also working with ocpp integration with esp32

**Comment by nb4787** [comment]
cdacndb@gmail.com

**Comment by matth-x** [comment]
Hi Ritu,

The package.json is not a part of this library, but belongs to the PlatformIO ecosystem. So probably your installation of the IDE is corrupted. In [this page](https://community.platformio.org/t/upload-error-could-not-find-one-of-package-json-manifest-files-in-the-package/28149) I found that reinstalling the toolchain could solve the issue.
