### ISSUE TITLE
Can you suggest how to change 4 minute to 1 minute for , for meter values update every minute to steve ?

### ISSUE THREAD

**Issue by nb4787** [matth-x/ArduinoOcpp#99]
i need to steve should update metervalues every minute ? Can you suggest explain

**Comment by matth-x** [comment]
There are two alternatives:

1. Change the Configuration `MeterValueSampleInterval` to 15s in your Central System. By default, the charger will send 4 MeterValues every minute then.
2. Alternatively, find [this line](https://github.com/matth-x/ArduinoOcpp/blob/10795aad7e124917a0336b4d98fd51b47c197453/src/ArduinoOcpp/Tasks/Metering/ConnectorMeterValuesRecorder.cpp#L23) in the source code. Change the 4 to 1, erase the flash memory and upload the firmware again.

**Comment by matth-x** [comment]
03177f93e7d2c6b6b15c07b5d0f9944da65512b0 addresses this issue. You can change the custom configuration `AO_MeterValueCacheSize` to 1 and then the charger will send each measurement immediately to the server.

**Comment by bananaslug123** [comment]
Anna, fyi I had to make a stop and traffic is tight.  I should be there by 4:30…Thanks,BrianOn Nov 13, 2022, at 10:30 AM, Matthias Akstaller ***@***.***> wrote:﻿
03177f9 addresses this issue. You can change the custom configuration AO_MeterValueCacheSize to 1 and then the charger will send each measurement immediately to the server.
